name: Hexo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Cache node_modules
      uses: actions/cache@v2
      env:
        cache-name: hexo-node-modules
      with:
        path: |
          node_modules
          themes/tranquilpeak/node_modules
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package.json') }}

    - name: Prepare node_modules
      run: |
        yarn
        cd themes/tranquilpeak
        yarn

    - name: Hexo Generate
      run: yarn hexo g

    - name: Deploy to Cloudflare Workers
      uses: cloudflare/wrangler-action@1.1.0
      with:
        apiToken: ${{ secrets.CF_WORKERS_TOKEN }}
      if: ${{ github.repository_owner == 'kinosang' && github.ref == 'refs/heads/master' }}

    - name: Deploy to GitHub.io
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
      if: ${{ github.repository_owner == 'kinosang' && github.ref == 'refs/heads/master' }}

    - name: Algolia Indexing
      env:
        ALGOLIA_ADMIN_API_KEY: ${{secrets.ALGOLIA_ADMIN_API_KEY}}
      run: yarn hexo a
      if: ${{ github.repository_owner == 'kinosang' && github.ref == 'refs/heads/master' }}
